### ISSUE TITLE
Colon in title breaks meta yaml parser

### ISSUE THREAD

**Issue by hacklschorsch** [klml/drfrederson#10]
One may not use a colon in page titles and descriptions. YaML sucks.

    PHP Fatal error:  Uncaught exception 'Exception' with message 'Too many keys: Referenzbeispiel einer Entfluchtungssimulation in Zusammenarbeit mit 4D-Event für eine historische Location: den Freisinger Dom.' in /home/fs-accu/accu-rate/Homepage/website/_drf/lib/spyc/Spyc.php:1043

**Comment by klml** [comment]
quote the string:

pagetitle: "Example page: for exemplary usage"

so you you get [it right](http://drf.grus.uberspace.de/drf:example)

> <title>Example page: for exemplary usage | another sitetitle from pagemeta</title>

**Comment by hacklschorsch** [comment]
My workaround: Wrap the description in quotes

**Comment by hacklschorsch** [comment]
ah shite I had the text ready but forgot to hit the "comment"  button. thanks!

**Comment by hacklschorsch** [comment]
that worked. I still think yaml sucks

**Comment by hacklschorsch** [comment]
Thanks for your super quick reply!
